### ISSUE TITLE
Getting an Error while running the app using React Hooks

### ISSUE THREAD

**Issue by aravindkarteek** [aravindkarteek/react-tetris#1]
I have been practicing creating react-tetris app from youtube where I got an error while running the app when using useState() hook. Error is attache.
![react-tetris-error-in-tetris-js](https://user-images.githubusercontent.com/50867399/63103337-89d7c980-bf9a-11e9-8cf3-5c8cd57e2f8e.png)

**Comment by sergeycw** [comment]
Hi man! I think I found the problem, check my pull request.
